### PR TITLE
Add pfSense config and usage notes

### PR DESCRIPTION
**Pull request by ajkavanagh**
This PR provides usage notes on how to build the tool using a FreeBSD build machine,
and then provides some scripts and instructions on how to configure the pfSense
router to autostart an instance of udp-broadcast-relay-redux on boot.

### CODE REVIEW

**Comment by ajkavanagh** [comment]
@riess82 I did put a section in the ToDo part of the readme about managing multiple instances.  if @sonicsnes would like to review/merge/reject it as-is, then you could add that bit perhaps?

**Comment by riess82** [comment]
So here is my example of multiple instances:

Once done with the guide from usage-notes/pfsense-config/README.md continue like this:
```
cd /usr/local/etc/rc.d
cp  udp-broadcast-relay.sh   udp-broadcast-relay2.sh
```
Rename your second instance variables.
```
nano udp-broadcast-relay.sh
```
_name="udp-broadcast-relay2"
rcvar="udp_broadcast_relay2_enable"
....
conf_file="/usr/local/etc/udp-broadcast-relay-redux2.conf"_

Next do the same with the config file:
```
cd /usr/local/etc/
cp udp-broadcast-relay-redux.conf udp-broadcast-relay-redux2.conf
nano udp-broadcast-relay-redux2.conf
```
AND CHANGE TO: _--id 2_ and whatever other ports and settings you need in your new instance.

Finally add the service:
```
nano /etc/rc.conf.local
```
and add a new line:
_udp_broadcast_relay2_enable=YES_


Rince and repeat as needed.

**Comment by sonicsnes** [comment]
Apologies for the enormous delay on this. While I do still use udp-broadcast-relay-redux extensively in my personal setup, I've been pretty passive on its development. @ajkavanagh I've added you as a collaborator, feel free to push changes as you see fit 😄

**Comment by ajkavanagh** [comment]
@sonicsnes thanks for adding me.  I'll avoid changing the core code, but I'll add in the change by @riess82 to my PR and then merge it, if that's okay.  Thanks!

**Pull request merged**
